-- 4_consulta_folha_pagamento
SELECT DISTINCT
    C.*
FROM (
    SELECT
        'DEBITO'                    AS SITUACAO,
        PCONTABILIZACAO.CODLOTE     AS COD_LOTE,
        PCONTABILIZACAO.DESCRICAO   AS DESC_LOTE,
        GCOLIGADA.CODCOLIGADA       AS COD_COLIGADA,
        GCOLIGADA.NOMEFANTASIA      AS NOME_COLIGADA,
        PFUNC.CODFILIAL             AS PCODFILIAL,
        PSECAO.CODFILIAL            AS COD_FILIAL,
        GFILIAL.NOME                AS NOME_FILIAL,
        --
        PFUNC.CODSECAO              AS COD_SETOR,
        PSECAO.DESCRICAO            AS NOME_SETOR,
        PFUNCAO.CODIGO              AS COD_CARGO,
        PFUNCAO.NOME                AS NOME_CARGO,
        --
        PCCUSTO.CODCCUSTO           AS COD_CUSTO,
        PCCUSTO.NOME                AS CENTRO_CUSTO,
        CCONTA.CODCONTA             AS COD_CONTA,
        CCONTA.DESCRICAO            AS DESC_CONTA,
        PPARTIDA.COMPLEMENTO        AS COMPLEMENTO,
        PITEMPARTIDA.VALOR * ( -1 ) AS VALOR,
        PFUNC.CHAPA                 AS CHAPA,
        PFUNC.NOME                  AS NOME_FUNCIONARIO,
--             (
--                 SELECT PTPFUNC.DESCRICAO
--                 FROM   PTPFUNC(NOLOCK)
--                 WHERE  PTPFUNC.CODCLIENTE = PFUNC.CODTIPO
--             )                           AS TIPO_FUNCIONARIO,
        CASE
             WHEN Substring(CCONTA.CODCONTA, 1, 1) = 1 THEN '1 - ATIVO'
             WHEN Substring(CCONTA.CODCONTA, 1, 1) = 2 THEN '2 - PASSIVO CIRCULANTE'
             WHEN Substring(CCONTA.CODCONTA, 1, 1) = 4 THEN '4 - CONTAS DE RESULTADO'
        END                         AS NIVEL
    FROM PCONTABILIZACAO(NOLOCK)
    INNER JOIN PPARTIDA (NOLOCK)
        ON PPARTIDA.CODCOLIGADA = PCONTABILIZACAO.CODCOLIGADA
        AND PPARTIDA.CODLOTE = PCONTABILIZACAO.CODLOTE
    INNER JOIN CCONTA (NOLOCK)
        ON CCONTA.CODCONTA = PPARTIDA.DEBITO
        AND CCONTA.CODCOLIGADA = PPARTIDA.CODCOLIGADA
    INNER JOIN GFILIAL
        ON GFILIAL.CODFILIAL = PPARTIDA.CODFILIAL
        AND GFILIAL.CODCOLIGADA = PPARTIDA.CODCOLIGADA
    INNER JOIN GCOLIGADA (NOLOCK)
        ON GCOLIGADA.CODCOLIGADA = GFILIAL.CODCOLIGADA
    LEFT JOIN PCCUSTO (NOLOCK)
        ON PCCUSTO.CODCOLIGADA = PPARTIDA.CODCOLIGADA
        AND PCCUSTO.CODCCUSTO = PPARTIDA.CODCCUSTO
    LEFT JOIN PITEMPARTIDA (NOLOCK)
        ON PITEMPARTIDA.CODCOLIGADA = PPARTIDA.CODCOLIGADA
        AND PITEMPARTIDA.IDPARTIDA = PPARTIDA.IDPARTIDA
        AND PITEMPARTIDA.CODLOTE = PPARTIDA.CODLOTE
    LEFT JOIN PFUNC
        ON PFUNC.CODCOLIGADA = PITEMPARTIDA.CODCOLIGADA
        AND PFUNC.CHAPA = PITEMPARTIDA.CHAPA
    INNER JOIN PFUNCAO (NOLOCK)
        ON PFUNCAO.CODIGO = PFUNC.CODFUNCAO
        AND PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA
    INNER JOIN PSECAO (NOLOCK)
        ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA
        AND PSECAO.CODIGO = PFUNC.CODSECAO

    UNION ALL

    SELECT
        'CREDITO'                   AS SITUACAO,
        PCONTABILIZACAO.CODLOTE     AS COD_LOTE,
        PCONTABILIZACAO.DESCRICAO   AS DESC_LOTE,
        GCOLIGADA.CODCOLIGADA       AS COD_COLIGADA,
        GCOLIGADA.NOMEFANTASIA      AS NOME_COLIGADA,
        PFUNC.CODFILIAL             AS PCODFILIAL,
        PSECAO.CODFILIAL            AS COD_FILIAL,
        GFILIAL.NOME                AS NOME_FILIAL,
        --
        PFUNC.CODSECAO              AS COD_SETOR,
        PSECAO.DESCRICAO            AS NOME_SETOR,
        PFUNCAO.CODIGO              AS COD_CARGO,
        PFUNCAO.NOME                AS NOME_CARGO,
        --
        PCCUSTO.CODCCUSTO           AS COD_CUSTO,
        PCCUSTO.NOME                AS CENTRO_CUSTO,
        CCONTA.CODCONTA             AS COD_CONTA,
        CCONTA.DESCRICAO            AS DESC_CONTA,
        PPARTIDA.COMPLEMENTO        AS COMPLEMENTO,
        PITEMPARTIDA.VALOR          AS VALOR,
        PFUNC.CHAPA                 AS CHAPA,
        PFUNC.NOME                  AS NOMEFUNC,
--         (
--             SELECT PTPFUNC.DESCRICAO
--             FROM   PTPFUNC(NOLOCK)
--             WHERE  PTPFUNC.CODCLIENTE = PFUNC.CODTIPO
--         )                           AS TIPOFUNCIONARIO,
        CASE
            WHEN Substring(CCONTA.CODCONTA, 1, 1) = 1 THEN '1 - ATIVO'
            WHEN Substring(CCONTA.CODCONTA, 1, 1) = 2 THEN '2 - PASSIVO CIRCULANTE'
            WHEN Substring(CCONTA.CODCONTA, 1, 1) = 4 THEN '4 - CONTAS DE RESULTADO'
        END                         AS NIVEL
    FROM PCONTABILIZACAO(NOLOCK)
    INNER JOIN PPARTIDA (NOLOCK)
        ON PPARTIDA.CODCOLIGADA = PCONTABILIZACAO.CODCOLIGADA
        AND PPARTIDA.CODLOTE = PCONTABILIZACAO.CODLOTE
    INNER JOIN CCONTA (NOLOCK)
        ON CCONTA.CODCONTA = PPARTIDA.CREDITO
        AND CCONTA.CODCOLIGADA = PPARTIDA.CODCOLIGADA
    LEFT JOIN PCCUSTO (NOLOCK)
        ON PCCUSTO.CODCOLIGADA = PPARTIDA.CODCOLIGADA
        AND PCCUSTO.CODCCUSTO = PPARTIDA.CODCCUSTO
    INNER JOIN GFILIAL (NOLOCK)
        ON GFILIAL.CODFILIAL = PPARTIDA.CODFILIAL
        AND GFILIAL.CODCOLIGADA = PPARTIDA.CODCOLIGADA
    INNER JOIN GCOLIGADA (NOLOCK)
        ON GCOLIGADA.CODCOLIGADA = GFILIAL.CODCOLIGADA
    LEFT JOIN PITEMPARTIDA (NOLOCK)
        ON PITEMPARTIDA.CODCOLIGADA = PPARTIDA.CODCOLIGADA
        AND PITEMPARTIDA.IDPARTIDA = PPARTIDA.IDPARTIDA
        AND PITEMPARTIDA.CODLOTE = PPARTIDA.CODLOTE
    LEFT JOIN PFUNC
        ON PFUNC.CODCOLIGADA = PITEMPARTIDA.CODCOLIGADA
        AND PFUNC.CHAPA = PITEMPARTIDA.CHAPA
    INNER JOIN PFUNCAO (NOLOCK)
        ON PFUNCAO.CODIGO = PFUNC.CODFUNCAO
        AND PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA
    INNER JOIN PSECAO (NOLOCK)
        ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA
        AND PSECAO.CODIGO = PFUNC.CODSECAO
) C
WHERE
    UPPER(C.NOME_FUNCIONARIO) LIKE '%MARIA FERNANDA CARVALHO DUARTE%'
ORDER BY
    C.COD_COLIGADA,
    C.NOME_FILIAL,
    C.CHAPA

